### ISSUE TITLE
bi önerim var

### ISSUE THREAD

**Issue by javav12** [isPique/Fuck-Windows-Security#1]
bu kod iyi fakat bence kodda bissürü bos kod veya "#" ekleyerek anti virisün tanımasını engeleye biliriz (çok fazla bilgi dosyanın boyutunu artırır buda anti virüsü bu dosyayı taramaması için iyi bir seçenektir)

**Comment by isPique** [comment]
Eğer bunu kodun kendisine yaparsam çok saçma olur. Yapılırsa .exe dosyasına dönüştürüldükten sonra yapılabilir ama onu da yapmak için onlarca program var zaten. Dosyanın içine tonlarca boş veri yazıp dosyanın boyutunu anti virüsün tarayamayacağı kadar büyütüyor.

**Comment by javav12** [comment]
haklısın aslında hem build leme süresi artar
