### ISSUE TITLE
Fun coincidence, we use the same disclaimer! 

### ISSUE THREAD

**Issue by loneicewolf** [isPique/Fuck-Windows-Security#2]
"malware ahead (..)"

Have a nice day!
Just thought it was nice To see such a coincidence, I admire those who make such a clear and concise disclaimer. 
Over n out!

**Comment by isPique** [comment]
umm u got me i saw that disclaimer from you :) it was really clear

**Comment by loneicewolf** [comment]
Oh it's okay! `:D` no worries, just happy someone else is using clear disclaimers, respect! 
Have a really Nice day! :D
